import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

void main() {
  test('every Android notification path uses the RingaPop small icon', () {
    final manifest = File(
      'android/app/src/main/AndroidManifest.xml',
    ).readAsStringSync();
    final scheduler = File(
      'lib/features/reminders/data/local_notifications_reminder_scheduler.dart',
    ).readAsStringSync();
    final alarmService = File(
      'android/app/src/main/kotlin/com/timeapp/time_app/reminders/'
      'AlarmSoundService.kt',
    ).readAsStringSync();

    expect(
      manifest,
      contains('android:resource="@drawable/ic_notification"'),
      reason: 'background FCM notifications need the branded default icon',
    );
    expect(
      scheduler,
      contains("AndroidInitializationSettings('ic_notification')"),
      reason: 'local notifications need the branded default icon',
    );
    expect(
      scheduler,
      contains("icon: 'ic_notification'"),
      reason: 'local notification details must select the branded icon',
    );
    expect(
      alarmService,
      contains('.setSmallIcon(R.drawable.ic_notification)'),
      reason: 'the native ringing notification must use the same icon',
    );
    expect(
      alarmService,
      isNot(contains('.setSmallIcon(applicationInfo.icon)')),
      reason: 'a full-colour launcher bitmap becomes a generic white blob',
    );
  });

  test('the small-icon resource is the generated RingaPop mark, white only '
      '(DECISIONS.md "RingaPop rebrand")', () {
    final icon = File(
      'android/app/src/main/res/drawable/ic_notification.xml',
    ).readAsStringSync();

    expect(icon, contains('GENERATED by scripts/generate_brand_icons.py'));
    final colours = RegExp(
      r'fillColor="([^"]+)"',
    ).allMatches(icon).map((m) => m.group(1)).toSet();
    expect(colours, {'#FFFFFFFF'}, reason: 'Android draws only the alpha');
  });

  test('the launcher icon is adaptive, with a themed-icon layer', () {
    for (final name in ['ic_launcher', 'ic_launcher_round']) {
      final xml = File(
        'android/app/src/main/res/mipmap-anydpi-v26/$name.xml',
      ).readAsStringSync();
      expect(xml, contains('@color/launcher_background'));
      expect(xml, contains('@drawable/ic_launcher_foreground'));
      expect(xml, contains('<monochrome'));
    }
    final colors = File(
      'android/app/src/main/res/values/colors.xml',
    ).readAsStringSync();
    expect(colors, contains('<color name="launcher_background">#FFEAF8EF'));
  });
}
