import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'precompiled_normalizer.dart';

/// The XLM-R tokenizer from `tokenizer.json`, on-device.
///
/// **The contract it has to honour.** The corpus index was embedded by the
/// Python pipeline: HuggingFace's fast tokenizer, `truncation=True,
/// max_length=128`. Query and index vectors are only comparable if both sides
/// tokenize identically, and a tokenizer that is *nearly* right produces no
/// error — just a query that lands slightly off and retrieves a worse line. So
/// this reproduces the four stages of that file rather than approximating them:
///
///  1. **Normalizer** — `Precompiled`, the SentencePiece charsmap
///     ([PrecompiledNormalizer]).
///  2. **Pre-tokenizer** — `WhitespaceSplit` then `Metaspace('▁',
///     prepend_scheme: always)`: split on Unicode whitespace, drop it, and
///     prefix every remaining run with `▁`.
///  3. **Model** — `Unigram`: a Viterbi search for the highest-scoring
///     segmentation over 250,002 scored pieces.
///  4. **Post-processor** — `TemplateProcessing`, wrapping the result in
///     `<s> … </s>`.
///
/// Correctness here is checked against goldens generated by the real
/// HuggingFace tokenizer (`test/chatbot_tokenizer_test.dart`), because the only
/// definition of "right" is "what the thing that built the index did".
class UnigramTokenizer {
  UnigramTokenizer._({
    required this.unkId,
    required this.bosId,
    required this.eosId,
    required double minScore,
    required this._normalizer,
    required this._pieceIds,
    required this._scores,
    required this._maxPieceChars,
  }) : _unkScore = minScore - _unkPenalty;

  /// Parse a `tokenizer.json`.
  ///
  /// Deliberately strict about the pieces it knows how to run: a file with a
  /// different normalizer or a different model type is not a variant to muddle
  /// through, it is a different tokenizer, and silently mis-tokenizing every
  /// query is a far worse failure than refusing to start.
  factory UnigramTokenizer.fromJson(Map<String, dynamic> json) {
    final model = json['model'];
    if (model is! Map || model['type'] != 'Unigram') {
      throw const FormatException(
          'tokenizer.json is not a Unigram model — this build cannot run it');
    }

    final normalizerJson = json['normalizer'];
    PrecompiledNormalizer? normalizer;
    if (normalizerJson is Map) {
      if (normalizerJson['type'] != 'Precompiled') {
        throw FormatException(
            'unsupported normalizer: ${normalizerJson['type']}');
      }
      normalizer = PrecompiledNormalizer.fromBase64(
          normalizerJson['precompiled_charsmap'] as String);
    }

    final vocab = model['vocab'];
    if (vocab is! List || vocab.isEmpty) {
      throw const FormatException('tokenizer.json has no vocabulary');
    }

    final pieceIds = <String, int>{};
    final scores = Float64List(vocab.length);
    var maxPieceChars = 1;
    var minScore = double.infinity;

    for (var id = 0; id < vocab.length; id++) {
      final entry = vocab[id] as List;
      final piece = entry[0] as String;
      final score = (entry[1] as num).toDouble();
      // First id wins. The reference builds its lookup the same way, and the
      // duplicate that matters — `<mask>` sharing a score with the specials —
      // must not displace an earlier piece.
      pieceIds.putIfAbsent(piece, () => id);
      scores[id] = score;
      if (score < minScore) minScore = score;
      final chars = piece.runes.length;
      if (chars > maxPieceChars) maxPieceChars = chars;
    }

    // The specials come from the post-processor rather than being assumed: the
    // template is what actually decides what wraps a sequence.
    var bosId = pieceIds['<s>'] ?? 0;
    var eosId = pieceIds['</s>'] ?? 2;
    final post = json['post_processor'];
    if (post is Map && post['type'] == 'TemplateProcessing') {
      final specials = post['special_tokens'];
      if (specials is Map) {
        bosId = _templateId(specials, '<s>') ?? bosId;
        eosId = _templateId(specials, '</s>') ?? eosId;
      }
    }

    return UnigramTokenizer._(
      normalizer: normalizer,
      pieceIds: pieceIds,
      scores: scores,
      maxPieceChars: maxPieceChars,
      unkId: (model['unk_id'] as num?)?.toInt() ?? 3,
      bosId: bosId,
      eosId: eosId,
      minScore: minScore,
    );
  }

  /// Read and parse a `tokenizer.json` off disk.
  ///
  /// The real file is 17MB of JSON. Parsing it costs a beat, which is why the
  /// engine loads once and is kept alive rather than rebuilt per message.
  static Future<UnigramTokenizer> load(File file) async {
    final text = await file.readAsString(encoding: utf8);
    final decoded = jsonDecode(text);
    if (decoded is! Map<String, dynamic>) {
      throw const FormatException('tokenizer.json is not an object');
    }
    return UnigramTokenizer.fromJson(decoded);
  }

  static int? _templateId(Map specials, String name) {
    final entry = specials[name];
    if (entry is! Map) return null;
    final ids = entry['ids'];
    if (ids is! List || ids.isEmpty) return null;
    return (ids.first as num).toInt();
  }

  /// The penalty applied to an unknown piece, from the reference implementation.
  /// Large enough that any real segmentation beats one that gives up.
  static const double _unkPenalty = 10;

  /// The sequence length the index was built at, specials included.
  static const int maxSequenceLength = 128;

  final PrecompiledNormalizer? _normalizer;
  final Map<String, int> _pieceIds;
  final Float64List _scores;
  final int _maxPieceChars;
  final double _unkScore;

  final int unkId;
  final int bosId;
  final int eosId;

  /// Token ids for [text], wrapped in the specials and truncated to
  /// [maxSequenceLength] — exactly what the ONNX graph expects as `input_ids`.
  Int64List encode(String text) {
    final ids = <int>[bosId];

    // The room left for real content. Truncation has to account for the
    // specials because the Python side counted them too: `max_length` there is
    // the length of the finished sequence, not of the middle of it.
    final budget = maxSequenceLength - 2;

    outer:
    for (final word in _preTokenize(_normalizer?.normalize(text) ?? text)) {
      for (final id in _viterbi(word)) {
        if (ids.length - 1 >= budget) break outer;
        ids.add(id);
      }
    }

    ids.add(eosId);
    return Int64List.fromList(ids);
  }

  /// `WhitespaceSplit` + `Metaspace`, which together reduce to: split on
  /// whitespace, drop the empties, and prefix each survivor with `▁`.
  ///
  /// Metaspace's usual job — turning interior spaces into `▁` — has nothing
  /// left to do here, because the whitespace split already removed every space.
  /// That is why this is one pass and not two.
  List<String> _preTokenize(String normalized) {
    final words = <String>[];
    final buffer = StringBuffer();

    void flush() {
      if (buffer.isEmpty) return;
      words.add('▁${buffer.toString()}');
      buffer.clear();
    }

    for (final rune in normalized.runes) {
      if (_isWhitespace(rune)) {
        flush();
      } else {
        buffer.writeCharCode(rune);
      }
    }
    flush();
    return words;
  }

  /// The highest-scoring segmentation of one pre-token, as ids.
  ///
  /// A plain Viterbi over character positions: `best[i]` is the score of the
  /// best path reaching character `i`. Every piece the vocabulary can start at
  /// a position competes, and the winner is read back from the end.
  ///
  /// Positions are **character** offsets, not UTF-16 code units, so an emoji is
  /// one position rather than two — otherwise a surrogate pair could be cut in
  /// half and the substring lookups would compare garbage.
  List<int> _viterbi(String word) {
    final chars = word.runes.toList(growable: false);
    final n = chars.length;
    if (n == 0) return const [];

    // Character offset -> UTF-16 offset, so a piece can be sliced out with one
    // substring call instead of rebuilding a string per candidate.
    final utf16Offset = List<int>.filled(n + 1, 0);
    var acc = 0;
    for (var i = 0; i < n; i++) {
      utf16Offset[i] = acc;
      acc += chars[i] > 0xFFFF ? 2 : 1;
    }
    utf16Offset[n] = acc;

    final best = Float64List(n + 1)..fillRange(1, n + 1, double.negativeInfinity);
    final backPos = Int32List(n + 1);
    final backId = Int32List(n + 1);
    // Whether the winning arc into a position was an unknown piece; needed
    // because adjacent unknowns are fused into one token at the end.
    final backUnk = List<bool>.filled(n + 1, false);

    for (var start = 0; start < n; start++) {
      if (best[start] == double.negativeInfinity) continue;

      var matchedSingle = false;
      final limit = (start + _maxPieceChars) < n ? start + _maxPieceChars : n;

      for (var end = start + 1; end <= limit; end++) {
        final piece =
            word.substring(utf16Offset[start], utf16Offset[end]);
        final id = _pieceIds[piece];
        if (id == null) continue;
        if (end - start == 1) matchedSingle = true;

        final score = best[start] + _scores[id];
        if (score > best[end]) {
          best[end] = score;
          backPos[end] = start;
          backId[end] = id;
          backUnk[end] = false;
        }
      }

      // The reference guarantees the lattice is always traversable by giving
      // every position a single-character escape hatch when the vocabulary
      // offers none. Without it a word containing one unknown character would
      // have no path at all.
      if (!matchedSingle) {
        final score = best[start] + _unkScore;
        if (score > best[start + 1]) {
          best[start + 1] = score;
          backPos[start + 1] = start;
          backId[start + 1] = unkId;
          backUnk[start + 1] = true;
        }
      }
    }

    // Walk the winners back, then reverse. Adjacent unknowns collapse into a
    // single `<unk>` (the reference's `fuse_unk`), so `🎉🎉` is one unknown
    // token and not two.
    final reversed = <int>[];
    var pos = n;
    var previousWasUnk = false;
    while (pos > 0) {
      final id = backId[pos];
      final isUnk = backUnk[pos];
      if (!(isUnk && previousWasUnk)) reversed.add(id);
      previousWasUnk = isUnk;
      pos = backPos[pos];
    }
    return reversed.reversed.toList(growable: false);
  }

  /// The Unicode `White_Space` property, enumerated.
  ///
  /// Enumerated rather than approximated with `trim`-style helpers because the
  /// reference splits on exactly this set. Most of these never survive
  /// normalization — the charsmap has already folded them to a plain space —
  /// but the ones that do must split, and being wrong here silently changes
  /// tokenization.
  static bool _isWhitespace(int rune) =>
      (rune >= 0x09 && rune <= 0x0D) ||
      rune == 0x20 ||
      rune == 0x85 ||
      rune == 0xA0 ||
      rune == 0x1680 ||
      (rune >= 0x2000 && rune <= 0x200A) ||
      rune == 0x2028 ||
      rune == 0x2029 ||
      rune == 0x202F ||
      rune == 0x205F ||
      rune == 0x3000;
}
