import 'package:cloud_firestore/cloud_firestore.dart';

import '../../../core/timezone/tz_resolver.dart';
import '../../scheduling/domain/schedule_item.dart';
import '../../social/domain/social_ids.dart';
import '../domain/plan_request.dart';

class PlanRequestRepository {
  PlanRequestRepository(this._db);

  final FirebaseFirestore _db;

  CollectionReference<Map<String, dynamic>> get _requests =>
      _db.collection('planRequests');

  CollectionReference<Map<String, dynamic>> _items(String uid) =>
      _db.collection('scheduleItems').doc(uid).collection('items');

  Stream<PlanRequest?> watchOne(String id) => _requests
      .doc(id)
      .snapshots()
      .map(
        (snapshot) => snapshot.exists ? PlanRequest.fromDoc(snapshot) : null,
      );

  Stream<List<PlanRequest>> watchIncoming(String plannerUid) {
    return _requests
        .where('plannerUid', isEqualTo: plannerUid)
        .snapshots()
        .map(
          (snapshot) =>
              snapshot.docs
                  .map(PlanRequest.fromDoc)
                  .where((request) => request.isOpen)
                  .toList()
                ..sort(
                  (a, b) => (b.createdAt ?? DateTime(0)).compareTo(
                    a.createdAt ?? DateTime(0),
                  ),
                ),
        );
  }

  Stream<List<PlanRequest>> watchOutgoing(String requesterUid) {
    return _requests
        .where('requesterUid', isEqualTo: requesterUid)
        .snapshots()
        .map(
          (snapshot) => snapshot.docs.map(PlanRequest.fromDoc).toList()
            ..sort(
              (a, b) => (b.createdAt ?? DateTime(0)).compareTo(
                a.createdAt ?? DateTime(0),
              ),
            ),
        );
  }

  /// Sends one independently actionable request to each selected friend.
  /// [batchId] is generated by the caller once and retained on retries; the
  /// deterministic `batchId_plannerUid` ids make replay an idempotent set.
  Future<void> createBatch({
    required String batchId,
    required String requesterUid,
    required List<String> plannerUids,
    required PlanRequestMode mode,
    required String timezone,
    required DateTime windowStartUtc,
    required DateTime windowEndUtc,
    required int durationMinutes,
    String? title,
    String? message,
  }) async {
    final unique = plannerUids.toSet().toList();
    // Each write's rule reads that recipient's friendship + grant. Ten keeps
    // the atomic batch within Firestore's 20 cross-document access-call cap.
    if (unique.isEmpty || unique.length > 10) {
      throw ArgumentError('Choose between 1 and 10 friends.');
    }
    if (!windowEndUtc.isAfter(windowStartUtc)) {
      throw ArgumentError('The request window must end after it starts.');
    }
    if (durationMinutes < 1 || durationMinutes > 1440) {
      throw ArgumentError('Duration must be between 1 minute and 24 hours.');
    }
    if (durationMinutes > windowEndUtc.difference(windowStartUtc).inMinutes) {
      throw ArgumentError('The plan does not fit inside the request window.');
    }

    final batch = _db.batch();
    for (final plannerUid in unique) {
      final id = PlanRequest.requestId(batchId, plannerUid);
      batch.set(_requests.doc(id), {
        'batchId': batchId,
        'requesterUid': requesterUid,
        'plannerUid': plannerUid,
        'participantUids': [requesterUid, plannerUid],
        'mode': mode.name,
        'status': PlanRequestStatus.pending.name,
        'timezone': timezone,
        'windowStartUtc': Timestamp.fromDate(windowStartUtc.toUtc()),
        'windowEndUtc': Timestamp.fromDate(windowEndUtc.toUtc()),
        'durationMinutes': durationMinutes,
        if (title?.trim().isNotEmpty ?? false) 'title': title!.trim(),
        if (message?.trim().isNotEmpty ?? false) 'message': message!.trim(),
        'fulfilledSpans': const <Map<String, Object>>[],
        'fulfilledItemIds': const <String>[],
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      });
    }
    await batch.commit();
  }

  Future<void> decline(PlanRequest request) => _settle(
    request,
    PlanRequestStatus.declined,
    actorUid: request.plannerUid,
  );

  Future<void> cancel(PlanRequest request) => _settle(
    request,
    PlanRequestStatus.cancelled,
    actorUid: request.requesterUid,
  );

  Future<void> completeFlexible(PlanRequest request) => _settle(
    request,
    PlanRequestStatus.fulfilled,
    actorUid: request.plannerUid,
  );

  Future<void> _settle(
    PlanRequest request,
    PlanRequestStatus status, {
    required String actorUid,
  }) {
    return _requests.doc(request.id).update({
      'status': status.name,
      'settledByUid': actorUid,
      'updatedAt': FieldValue.serverTimestamp(),
    });
  }

  /// Creates one normal, pending schedule item and advances its request in the
  /// same transaction. Friendship and the target-authored normal grant are read
  /// again inside the transaction, so a revoke/unfriend while the form is open
  /// fails before either write lands.
  Future<String> fulfill({
    required PlanRequest request,
    required String plannerUid,
    required String title,
    String? note,
    required DateTime wall,
    required int durationMinutes,
    bool finishFlexibleRequest = false,
  }) async {
    if (plannerUid != request.plannerUid) {
      throw StateError('This request belongs to another planner.');
    }
    final instant = resolveWallTimeToUtc(wall, request.timezone);
    if (!spanFitsPlanRequest(
      request,
      startUtc: instant,
      durationMinutes: durationMinutes,
    )) {
      throw StateError('That plan does not fit the open request window.');
    }

    final requestRef = _requests.doc(request.id);
    final friendshipRef = _db
        .collection('friendships')
        .doc(friendshipId(plannerUid, request.requesterUid));
    final grantRef = friendshipRef
        .collection('plannerGrants')
        .doc('${plannerUid}_${request.requesterUid}');
    final itemRef = _items(request.requesterUid).doc();

    await _db.runTransaction((transaction) async {
      final requestSnapshot = await transaction.get(requestRef);
      final live = PlanRequest.fromDoc(requestSnapshot);
      final friendship = await transaction.get(friendshipRef);
      final grant = await transaction.get(grantRef);
      if (!friendship.exists || grant.data()?['granted'] != true) {
        throw StateError('Planning permission is no longer active.');
      }
      if (live.plannerUid != plannerUid ||
          live.requesterUid != request.requesterUid ||
          !spanFitsPlanRequest(
            live,
            startUtc: instant,
            durationMinutes: durationMinutes,
          )) {
        throw StateError('This request changed or is no longer available.');
      }

      final span = RequestedPlanSpan(
        itemId: itemRef.id,
        startUtc: instant,
        durationMinutes: durationMinutes,
      );
      final spans = [...live.fulfilledSpans, span];
      final fulfilled = live.isOnePlan || finishFlexibleRequest;

      transaction.set(itemRef, {
        'targetUid': live.requesterUid,
        'createdByUid': plannerUid,
        'groupId': '',
        'title': sanitizeScheduleTitle(title),
        if (note?.trim().isNotEmpty ?? false) 'note': note!.trim(),
        'localWallTime': formatWallTime(wall),
        'timezone': live.timezone,
        'scheduledInstantUtc': Timestamp.fromDate(instant),
        'durationMinutes': durationMinutes,
        'planRequestId': live.id,
        'status': ScheduleItemStatus.pending.name,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      });
      transaction.update(requestRef, {
        'status': fulfilled
            ? PlanRequestStatus.fulfilled.name
            : PlanRequestStatus.inProgress.name,
        'fulfilledSpans': [for (final value in spans) value.toMap()],
        'fulfilledItemIds': [for (final value in spans) value.itemId],
        'lastFulfilledItemId': itemRef.id,
        if (fulfilled) 'settledByUid': plannerUid,
        'updatedAt': FieldValue.serverTimestamp(),
      });
    });
    return itemRef.id;
  }
}
