import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:timezone/data/latest_all.dart' as tzdata;

import 'app.dart';
import 'firebase_options.dart';

Future<void> main() async {
  // Required before any async work in main().
  WidgetsFlutterBinding.ensureInitialized();

  // Connect to the Firebase project (config generated by `flutterfire configure`).
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Load the IANA timezone database into memory so we can (a) list zones in the
  // profile picker and (b) resolve local times later. Must run once at startup.
  tzdata.initializeTimeZones();

  // ProviderScope is the root of Riverpod — every provider lives under it.
  runApp(const ProviderScope(child: TimeApp()));
}
