import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/date_symbol_data_local.dart';
import 'package:timezone/data/latest_all.dart' as tzdata;

import 'app.dart';
import 'features/notifications/application/messaging_service.dart';
import 'firebase_options.dart';

Future<void> main() async {
  // Required before any async work in main().
  final binding = WidgetsFlutterBinding.ensureInitialized();

  // Connect to the Firebase project (config generated by `flutterfire configure`).
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Crashlytics: route both error channels to Firebase so crashes/errors on a
  // friend's phone are visible remotely (no USB/logcat needed). Framework build
  // errors go through FlutterError.onError; async + platform errors that escape
  // the zone go through platformDispatcher.onError.
  FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;
  binding.platformDispatcher.onError = (error, stack) {
    FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
    return true;
  };

  // Must be registered before runApp so FCM can deliver to a backgrounded /
  // terminated app. Handler is a top-level function (see messaging_service.dart).
  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);

  // Load the IANA timezone database into memory so we can (a) list zones in the
  // profile picker and (b) resolve local times later. Must run once at startup.
  tzdata.initializeTimeZones();

  // Load locale date/time symbols so DateFormat can render in any device locale
  // (see core/format/datetime_format.dart).
  await initializeDateFormatting();

  // ProviderScope is the root of Riverpod — every provider lives under it.
  runApp(const ProviderScope(child: TimeApp()));
}
