#!/usr/bin/env python3
"""Generates every Mind Time icon from the one master, assets/brand/mind_time_mark.svg.

Run from the repo root after changing the master:

    python3 scripts/generate_brand_icons.py

Needs ImageMagick (`magick`) for the PNGs. See DECISIONS.md "RingaPop rebrand
(2026-09-28)" for why each output looks the way it does. Summary:

- Android 8+ adaptive icon: a full-bleed mint BACKGROUND colour + the mark as a
  vector FOREGROUND scaled so every point sits inside the 66 dp safe circle of
  the 108 dp layer, so no launcher mask (circle, squircle, teardrop) ever cuts
  the mark itself.
- Android 13+ themed icon: a one-colour MONOCHROME layer (the clock face is left
  transparent, so the ring and hands still read once the system tints it).
- Android 7 and older: legacy PNG ic_launcher / ic_launcher_round per density.
- Notification small icon: white-on-transparent vector (Android draws only its
  alpha channel).
- iOS AppIcon set and the Play Store 512 px icon: mint full-bleed squares (both
  stores apply their own mask and reject transparency).
- The splash screen's tile: assets/brand/mind_time_icon.png.
"""

import math
import os
import re
import subprocess
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MASTER = os.path.join(ROOT, 'assets/brand/mind_time_mark.svg')
RES = os.path.join(ROOT, 'android/app/src/main/res')
IOS = os.path.join(ROOT, 'ios/Runner/Assets.xcassets/AppIcon.appiconset')

MINT = '#EAF8EF'  # lightBackground in lib/core/theme/app_colors.dart

# The master is a 1000 x 1000 box with the mark centred in it.
_master = open(MASTER).read()
FACE = re.search(r'id="face"[^>]*d="([^"]+)"', _master).group(1)
GREEN = re.search(r'id="green"[^>]*d="([^"]+)"', _master).group(1)
WAVES = re.search(r'id="waves"[^>]*d="([^"]+)"', _master).group(1)
FACE_FILL = re.search(r'id="face" fill="([^"]+)"', _master).group(1)
GREEN_FILL = re.search(r'id="green" fill="([^"]+)"', _master).group(1)
WAVES_FILL = re.search(r'id="waves" fill="([^"]+)"', _master).group(1)

_points = [
    (float(x), float(y))
    for d in (FACE, GREEN, WAVES)
    for x, y in re.findall(r'([\d.]+),([\d.]+)', d)
]
# Furthest point of the mark from its centre, in master units.
MAX_RADIUS = max(math.hypot(x - 500, y - 500) for x, y in _points)


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write(text)
    print('wrote', os.path.relpath(path, ROOT))


# ---- Android vectors ---------------------------------------------------------


def vector(size_dp, viewport, mark_scale, layers, comment):
    """A VectorDrawable of [layers] ((pathData, colour, evenOdd)), the 1000-unit
    master scaled by [mark_scale] and centred in a [viewport] square."""
    offset = viewport / 2 - 500 * mark_scale
    paths = '\n'.join(
        f'''        <path
            android:fillColor="{colour}"{'''
            android:fillType="evenOdd"''' if even_odd else ''}
            android:pathData="{data}" />'''
        for data, colour, even_odd in layers
    )
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by scripts/generate_brand_icons.py from
     assets/brand/mind_time_mark.svg. Edit the master, not this file.
     {comment} -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{size_dp}dp"
    android:height="{size_dp}dp"
    android:viewportWidth="{viewport}"
    android:viewportHeight="{viewport}">
    <group
        android:translateX="{offset:.4f}"
        android:translateY="{offset:.4f}"
        android:scaleX="{mark_scale:.6f}"
        android:scaleY="{mark_scale:.6f}">
{paths}
    </group>
</vector>
'''


def argb(hex_rgb):
    return '#FF' + hex_rgb.lstrip('#').upper()


# Every point inside a 64 dp circle: the 66 dp safe zone, less 1 dp either side.
ADAPTIVE_SCALE = 32 / MAX_RADIUS

write(
    os.path.join(RES, 'drawable/ic_launcher_foreground.xml'),
    vector(
        108, 108, ADAPTIVE_SCALE,
        [
            (FACE, argb(FACE_FILL), False),
            (GREEN, argb(GREEN_FILL), True),
            (WAVES, argb(WAVES_FILL), False),
        ],
        'Adaptive-icon foreground: every point inside the 66 dp safe circle.',
    ),
)
write(
    os.path.join(RES, 'drawable/ic_launcher_monochrome.xml'),
    vector(
        108, 108, ADAPTIVE_SCALE,
        [(GREEN, '#FF000000', True), (WAVES, '#FF000000', False)],
        'Android 13+ themed icon: one colour, tinted by the system. The face is\n'
        '     left transparent so the ring and hands still read.',
    ),
)
write(
    os.path.join(RES, 'drawable/ic_notification.xml'),
    vector(
        24, 24, 22 / 1000,
        [(GREEN, '#FFFFFFFF', True), (WAVES, '#FFFFFFFF', False)],
        'Notification small icon. Android draws ONLY the alpha channel and tints\n'
        '     it, so this is white on transparent; a colour bitmap here becomes a\n'
        '     solid blob. The face is transparent so the ring and hands read.',
    ),
)
adaptive = '''<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by scripts/generate_brand_icons.py. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
'''
write(os.path.join(RES, 'mipmap-anydpi-v26/ic_launcher.xml'), adaptive)
write(os.path.join(RES, 'mipmap-anydpi-v26/ic_launcher_round.xml'), adaptive)


# ---- PNGs ----------------------------------------------------------------------


def svg(px, background, mark_fraction):
    """[px] square: [background] ('square', 'rounded', 'circle' or None) with the
    mark [mark_fraction] of the width, centred."""
    s = px * mark_fraction / 1000
    o = px / 2 - 500 * s
    bg = {
        None: '',
        'square': f'<rect width="{px}" height="{px}" fill="{MINT}"/>',
        'rounded': f'<rect width="{px}" height="{px}" rx="{px * 0.18:.2f}" '
                   f'fill="{MINT}"/>',
        'circle': f'<circle cx="{px / 2}" cy="{px / 2}" r="{px / 2}" '
                  f'fill="{MINT}"/>',
    }[background]
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="{px}" height="{px}" viewBox="0 0 {px} {px}">
{bg}
<g transform="translate({o:.3f} {o:.3f}) scale({s:.6f})">
<path fill="{FACE_FILL}" d="{FACE}"/>
<path fill="{GREEN_FILL}" fill-rule="evenodd" d="{GREEN}"/>
<path fill="{WAVES_FILL}" d="{WAVES}"/>
</g>
</svg>'''


def png(path, px, background, mark_fraction, alpha=True):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with tempfile.NamedTemporaryFile('w', suffix='.svg', delete=False) as f:
        f.write(svg(px, background, mark_fraction))
        src = f.name
    args = ['magick', '-background', 'none', src]
    if not alpha:  # iOS / Play: no transparency allowed
        args += ['-background', MINT, '-alpha', 'remove', '-alpha', 'off']
    subprocess.run(args + [path], check=True)
    os.unlink(src)
    print('wrote', os.path.relpath(path, ROOT))


# Android 7 and older: the launcher shows these as they are.
for density, px in {
    'mdpi': 48, 'hdpi': 72, 'xhdpi': 96, 'xxhdpi': 144, 'xxxhdpi': 192,
}.items():
    png(os.path.join(RES, f'mipmap-{density}/ic_launcher.png'), px, 'rounded', 0.74)
    png(os.path.join(RES, f'mipmap-{density}/ic_launcher_round.png'), px, 'circle', 0.64)
    stale = os.path.join(RES, f'mipmap-{density}/ic_launcher_foreground.png')
    if os.path.exists(stale):
        os.remove(stale)  # replaced by drawable/ic_launcher_foreground.xml
        print('removed', os.path.relpath(stale, ROOT))

# iOS: every size already listed in the set's Contents.json.
for name in sorted(os.listdir(IOS)):
    m = re.match(r'Icon-App-([\d.]+)x[\d.]+@(\d)x\.png$', name)
    if m:
        px = round(float(m.group(1)) * int(m.group(2)))
        png(os.path.join(IOS, name), px, 'square', 0.72, alpha=False)

png(os.path.join(ROOT, 'assets/brand/mind_time_play_store_512.png'), 512, 'square', 0.72,
    alpha=False)
png(os.path.join(ROOT, 'assets/brand/mind_time_icon.png'), 432, 'rounded', 0.74)
