#!/usr/bin/env python3
"""Generates lib/core/format/zone_ids.dart from the system tz database.

    python3 scripts/generate_timezones.py [/usr/share/zoneinfo]

Why (DECISIONS.md "One name per timezone", 2026-09-28): phones report a zone by
whichever IANA name their OS ships, and many Android builds still say
"Asia/Calcutta" where others say "Asia/Kolkata". Both are the same zone; the
old one is a backward-compatibility LINK. The picker also listed every link, so
each renamed zone appeared twice.

- The picker offers exactly the zones in `zone.tab` (one per region, current
  names) plus Etc/UTC.
- Every link whose name is NOT in that list maps to its target, so an old name
  from a phone, or already saved, reads as the current one everywhere.
"""

import os
import sys

ZONEINFO = sys.argv[1] if len(sys.argv) > 1 else '/usr/share/zoneinfo'
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'lib/core/format/zone_ids.dart')

version = 'unknown'
links = {}  # alias -> target
zones = set()
for line in open(os.path.join(ZONEINFO, 'tzdata.zi')):
    if line.startswith('# version'):
        version = line.split()[-1]
    parts = line.split()
    if parts[:1] == ['Z']:
        zones.add(parts[1])
    elif parts[:1] == ['L']:
        links[parts[2]] = parts[1]

picker = sorted(
    {
        line.split('\t')[2].strip()
        for line in open(os.path.join(ZONEINFO, 'zone.tab'))
        if not line.startswith('#') and line.strip()
    }
    | {'Etc/UTC'}
)
picker_set = set(picker)


def resolve(name):
    seen = set()
    while name in links and name not in picker_set and name not in seen:
        seen.add(name)
        name = links[name]
    return name


aliases = {}
for alias in sorted(links):
    if alias in picker_set:
        continue  # a current name in its own right (e.g. Europe/Oslo)
    target = resolve(alias)
    if target in picker_set:
        aliases[alias] = target

body = '\n'.join(f"  '{z}'," for z in picker)
alias_body = '\n'.join(f"  '{a}': '{t}'," for a, t in aliases.items())
dart = f'''// GENERATED by scripts/generate_timezones.py from tzdata {version}.
// Do not edit by hand; re-run the script. DECISIONS.md "One name per timezone".

import 'package:timezone/timezone.dart' as tz;

/// The zones the picker offers: one per region, current IANA names
/// (`zone.tab`), plus Etc/UTC. No backward-compatibility aliases.
const kPickerZones = <String>[
{body}
];

/// Old or alias IANA names → the current name for the same zone
/// (e.g. `Asia/Calcutta` → `Asia/Kolkata`, `US/Eastern` → `America/New_York`).
const kZoneAliases = <String, String>{{
{alias_body}
}};

/// The one name used for [zone] everywhere: an old alias becomes its current
/// name. Unchanged when the loaded tz data does not know the current name, so
/// a zone can never become unresolvable.
String canonicalZone(String zone) {{
  final current = kZoneAliases[zone];
  if (current == null) return zone;
  final db = tz.timeZoneDatabase.locations;
  return db.isEmpty || db.containsKey(current) ? current : zone;
}}
'''
open(OUT, 'w').write(dart)
print(f'wrote {os.path.relpath(OUT, ROOT)}: {len(picker)} zones, {len(aliases)} aliases (tzdata {version})')
